import {
  Activity,
  Brain,
  Crosshair,
  Flame,
  Heart,
  Moon,
} from 'lucide-react';

export const FILM_CATEGORIES = [
  { id: 'burnout', labelKey: 'filmCatBurnout', Icon: Flame },
  { id: 'anxiety', labelKey: 'filmCatAnxiety', Icon: Brain },
  { id: 'stress', labelKey: 'filmCatStress', Icon: Activity },
  { id: 'sleep', labelKey: 'filmCatSleep', Icon: Moon },
  { id: 'focus', labelKey: 'filmCatFocus', Icon: Crosshair },
  { id: 'motivation', labelKey: 'filmCatMotivation', Icon: Heart },
];

export function filmSectionDescKey(categoryId) {
  return `filmSectionDesc${categoryId.charAt(0).toUpperCase() + categoryId.slice(1)}`;
}

/** @typedef {{ id: string, title: string, source: string, duration: string, year: string, rating: string, categoryId: string, psychTag: string, genres: string, description: string, poster: string, embedUrl: string, watchUrl: string, country?: string, director?: string, screenwriter?: string, gallery?: string[], quote?: string }} Film */

/** @type {Film[]} */
export const FILMS = [
  {
    id: 'f1',
    title: 'Soul',
    source: 'Pixar',
    duration: '1:40:00',
    year: '2020',
    rating: '8.0',
    categoryId: 'stress',
    psychTag: 'antistress',
    genres: 'Драма · Вдохновение',
    tags: {
      mood: ['relax', 'inspire', 'anxiety'],
      genre: ['drama', 'animation'],
      type: ['cartoon'],
      atmosphere: ['calm', 'inspiring', 'warm', 'aesthetic'],
    },
    description:
      'Теплая история о смысле жизни, вдохновении и внутреннем спокойствии. Хорошо подходит, когда нужно мягко снизить тревогу.',
    poster: 'https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/xOsLIiBStEs',
    watchUrl: 'https://www.youtube.com/watch?v=xOsLIiBStEs',
    country: 'США',
    director: 'Пит Доктер, Кемп Пауэрс',
    screenwriter: 'Пит Доктер, Майк Джонс, Кемп Пауэрс',
  },
  {
    id: 'f2',
    title: 'The Secret Life of Walter Mitty',
    source: '20th Century Fox',
    duration: '1:54:00',
    year: '2013',
    rating: '7.3',
    categoryId: 'burnout',
    psychTag: 'motivating',
    genres: 'Приключения · Мотивация',
    tags: {
      mood: ['inspire', 'tired', 'lift'],
      genre: ['adventure', 'drama'],
      type: ['feature'],
      atmosphere: ['light', 'inspiring', 'warm', 'nostalgia'],
    },
    description:
      'Фильм про внутренний перезапуск и смелость менять рутину. Отличный выбор при ощущении усталости и выгорания.',
    poster: 'https://image.tmdb.org/t/p/w500/cAh2pCiNPftsY3aSqJuIOde7uWr.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/HddkucqSzSM',
    watchUrl: 'https://rezka-ua.pub/films/adventures/1230-neveroyatnaya-zhizn-uoltera-mitti-2013.html',
    country: 'США',
    director: 'Бен Стиллер',
    screenwriter: 'Стив Конрад',
  },
  {
    id: 'f3',
    title: 'Spirited Away',
    source: 'Studio Ghibli',
    duration: '2:05:00',
    year: '2001',
    rating: '8.6',
    categoryId: 'sleep',
    psychTag: 'light',
    genres: 'Фэнтези · Спокойствие',
    tags: {
      mood: ['relax', 'anxiety', 'cozy', 'distract'],
      genre: ['fantasy', 'animation'],
      type: ['anime', 'cartoon'],
      atmosphere: ['aesthetic', 'calm', 'warm', 'cozy_a', 'nostalgia'],
    },
    description:
      'Медитативная атмосфера и красивый визуал помогают расслабиться перед сном и снизить внутреннее напряжение.',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ByXuk9QqQkk',
    watchUrl: 'https://www.youtube.com/watch?v=ByXuk9QqQkk',
    country: 'Япония',
    director: 'Хаяо Миядзаки',
    screenwriter: 'Хаяо Миядзаки',
    quote:
      'Иногда кажется, что всё вокруг - как во сне: что-то большее, чем просто красивый вид.',
  },
  {
    id: 'f4',
    title: 'The Social Network',
    source: 'Columbia Pictures',
    duration: '2:00:00',
    year: '2010',
    rating: '7.8',
    categoryId: 'focus',
    psychTag: 'motivating',
    genres: 'Биография · Фокус',
    tags: {
      mood: ['inspire', 'lift'],
      genre: ['drama'],
      type: ['feature'],
      atmosphere: ['light', 'calm'],
    },
    description:
      'Динамичный, но структурный фильм, который помогает собраться и вернуть концентрацию перед работой или учебой.',
    poster: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/lB95KLmpLR4',
    watchUrl: 'https://www.youtube.com/watch?v=lB95KLmpLR4',
    country: 'США',
    director: 'Дэвид Финчер',
    screenwriter: 'Аарон Соркин',
  },
  {
    id: 'f5',
    title: 'Julie & Julia',
    source: 'Columbia Pictures',
    duration: '2:03:00',
    year: '2009',
    rating: '7.0',
    categoryId: 'burnout',
    psychTag: 'light',
    genres: 'Драма · Восстановление',
    tags: {
      mood: ['cozy', 'tired', 'inspire'],
      genre: ['drama', 'romance', 'slice'],
      type: ['feature'],
      atmosphere: ['cozy_a', 'warm', 'light', 'nostalgia'],
    },
    description:
      'Легкий вдохновляющий сюжет про поиск себя и радость в простых шагах. Подходит для мягкого восстановления.',
    poster: 'https://image.tmdb.org/t/p/w500/AcY6HVE7Wv6f0vU7q5tQJgM6Y5A.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/DD8zMdn8LsQ',
    watchUrl: 'https://www.youtube.com/watch?v=DD8zMdn8LsQ',
    country: 'США',
    director: 'Нора Эфрон',
    screenwriter: 'Нора Эфрон',
  },
  {
    id: 'f6',
    title: 'Inside Out',
    source: 'Pixar',
    duration: '1:35:00',
    year: '2015',
    rating: '8.1',
    categoryId: 'anxiety',
    psychTag: 'emotional_release',
    genres: 'Психология · Эмоции',
    tags: {
      mood: ['anxiety', 'inspire', 'lift'],
      genre: ['animation', 'family'],
      type: ['cartoon'],
      atmosphere: ['light', 'warm', 'inspiring', 'calm'],
    },
    description: 'Фильм про эмоции и их принятие. Помогает лучше понять себя и снизить тревожные реакции.',
    poster: 'https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/yRUAzGQ3nSY',
    watchUrl: 'https://www.youtube.com/watch?v=yRUAzGQ3nSY',
    country: 'США',
    director: 'Пит Доктер, Роналдо Дель Кармен',
    screenwriter: 'Пит Доктер, Мег Лефов, Джош Кули',
  },
  {
    id: 'f7',
    title: 'The Intern',
    source: 'Warner Bros.',
    duration: '2:01:00',
    year: '2015',
    rating: '7.1',
    categoryId: 'burnout',
    psychTag: 'light',
    genres: 'Комедия · Поддержка',
    tags: {
      mood: ['tired', 'cozy', 'lift'],
      genre: ['comedy', 'drama'],
      type: ['feature'],
      atmosphere: ['warm', 'cozy_a', 'light'],
    },
    description:
      'Добрая история про баланс жизни и работы. Дает ощущение поддержки, когда эмоциональный ресурс на нуле.',
    poster: 'https://image.tmdb.org/t/p/w500/9U7YHooiXv3xR3xBvY8QnD8QfJk.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ZU3Xban0Y6A',
    watchUrl: 'https://www.youtube.com/watch?v=ZU3Xban0Y6A',
    country: 'США',
    director: 'Нэнси Майерс',
    screenwriter: 'Нэнси Майерс',
  },
  {
    id: 'f8',
    title: 'Midnight in Paris',
    source: 'Sony Pictures',
    duration: '1:34:00',
    year: '2011',
    rating: '7.6',
    categoryId: 'sleep',
    psychTag: 'light',
    genres: 'Романтика · Легкость',
    tags: {
      mood: ['cozy', 'relax', 'distract', 'anxiety'],
      genre: ['romance', 'drama', 'romcom'],
      type: ['feature'],
      atmosphere: ['aesthetic', 'calm', 'cozy_a', 'warm', 'light', 'nostalgia'],
    },
    description:
      'Уютное настроение и мягкий темп помогают переключиться и подготовиться ко сну без перегруза.',
    poster: 'https://image.tmdb.org/t/p/w500/4wBG5kbfagTQclETblPRRGihk0I.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/FAfR8omt-CY',
    watchUrl: 'https://www.youtube.com/watch?v=FAfR8omt-CY',
    country: 'США · Франция',
    director: 'Вуди Аллен',
    screenwriter: 'Вуди Аллен',
  },
  {
    id: 'f9',
    title: 'A Beautiful Mind',
    source: 'Universal Pictures',
    duration: '2:15:00',
    year: '2001',
    rating: '8.2',
    categoryId: 'anxiety',
    psychTag: 'antistress',
    genres: 'Биография · Драма',
    tags: {
      mood: ['anxiety', 'inspire'],
      genre: ['drama'],
      type: ['feature'],
      atmosphere: ['calm', 'inspiring'],
    },
    description: 'Глубокая история о борьбе с тревогой и сохранении внутренней устойчивости в сложные периоды.',
    poster: 'https://image.tmdb.org/t/p/w500/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/aS_d0Ayjw4o',
    watchUrl: 'https://www.youtube.com/watch?v=aS_d0Ayjw4o',
    country: 'США',
    director: 'Рон Ховард',
    screenwriter: 'Акива Голдсман',
  },
  {
    id: 'f10',
    title: 'The Pursuit of Happyness',
    source: 'Columbia Pictures',
    duration: '1:57:00',
    year: '2006',
    rating: '8.0',
    categoryId: 'motivation',
    psychTag: 'motivating',
    genres: 'Мотивация · Драма',
    tags: {
      mood: ['inspire', 'tired'],
      genre: ['drama'],
      type: ['feature'],
      atmosphere: ['inspiring', 'warm'],
    },
    description:
      'Сильный мотивирующий фильм для периодов выгорания, когда важно вернуть веру в себя и свои шаги.',
    poster: 'https://image.tmdb.org/t/p/w500/lBYOKAMcxIvuk9s9hMuecB9dPBV.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/89Kq8SDyvfg',
    watchUrl: 'https://www.youtube.com/watch?v=89Kq8SDyvfg',
    country: 'США',
    director: 'Габриэле Муччино',
    screenwriter: 'Стив Конрад',
  },
  {
    id: 'f11',
    title: 'Up',
    source: 'Pixar',
    duration: '1:36:00',
    year: '2009',
    rating: '8.3',
    categoryId: 'sleep',
    psychTag: 'emotional_release',
    genres: 'Семейный · Теплый',
    tags: {
      mood: ['cozy', 'anxiety', 'relax'],
      genre: ['animation', 'family'],
      type: ['cartoon'],
      atmosphere: ['warm', 'cozy_a', 'calm', 'nostalgia'],
    },
    description:
      'Очень мягкий и теплый фильм, который помогает снять эмоциональный фон и настроиться на спокойный сон.',
    poster: 'https://image.tmdb.org/t/p/w500/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ORFWdXl_zJ4',
    watchUrl: 'https://www.youtube.com/watch?v=ORFWdXl_zJ4',
    country: 'США',
    director: 'Пит Доктер, Боб Питерсон',
    screenwriter: 'Пит Доктер, Боб Питерсон',
  },
  {
    id: 'f12',
    title: 'Whiplash',
    source: 'Sony Pictures Classics',
    duration: '1:47:00',
    year: '2014',
    rating: '8.5',
    categoryId: 'stress',
    psychTag: 'emotional_release',
    genres: 'Музыка · Концентрация',
    tags: {
      mood: ['lift', 'inspire'],
      genre: ['drama'],
      type: ['feature'],
      atmosphere: ['inspiring', 'light'],
    },
    description: 'Заряжает энергией и помогает сфокусироваться на цели. Хорошо подходит для режима продуктивности.',
    poster: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/7d_jQycdQGo',
    watchUrl: 'https://www.youtube.com/watch?v=7d_jQycdQGo',
    country: 'США',
    director: 'Дэмьен Шазелл',
    screenwriter: 'Дэмьен Шазелл',
  },
  {
    id: 'f13',
    title: 'Амели',
    source: 'UGC Fox Distribution',
    duration: '2:02:00',
    year: '2001',
    rating: '8.3',
    categoryId: 'sleep',
    psychTag: 'light',
    genres: 'Романтика · Фантазия',
    tags: {
      mood: ['relax', 'cozy', 'inspire', 'distract'],
      genre: ['comedy', 'romance', 'drama', 'slice'],
      type: ['feature'],
      atmosphere: ['aesthetic', 'warm', 'light', 'nostalgia', 'calm', 'cozy_a'],
    },
    description:
      'Сказка о доброте и маленьких чудесах в обычной жизни. Поднимает настроение и даёт ощущение лёгкости и уюта.',
    poster: 'https://upload.wikimedia.org/wikipedia/en/5/53/Amelie_poster.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/sECz69OwVR0',
    watchUrl: 'https://www.youtube.com/watch?v=sECz69OwVR0',
    country: 'Франция · Германия',
    director: 'Жан-Пьер Жёне',
    screenwriter: 'Жан-Пьер Жёне, Гийом Лоран',
  },
  {
    id: 'f14',
    title: '1+1',
    source: 'Gaumont',
    duration: '1:52:00',
    year: '2011',
    rating: '8.5',
    categoryId: 'motivation',
    psychTag: 'motivating',
    genres: 'Драма · Комедия',
    tags: {
      mood: ['lift', 'inspire', 'tired', 'cozy'],
      genre: ['comedy', 'drama'],
      type: ['feature'],
      atmosphere: ['warm', 'light', 'inspiring', 'nostalgia', 'calm'],
    },
    description:
      'История дружбы и принятия. Заряжает теплом и верой в людей - хороший фильм, когда нужна поддержка и мотивация.',
    poster: 'https://upload.wikimedia.org/wikipedia/en/9/93/The_Intouchables.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/34WIbmXk7-0',
    watchUrl: 'https://www.youtube.com/watch?v=34WIbmXk7-0',
    country: 'Франция',
    director: 'Оливье Накаш, Эрик Толедано',
    screenwriter: 'Оливье Накаш, Эрик Толедано',
  },
  {
    id: 'f15',
    title: 'Форрест Гамп',
    source: 'Paramount Pictures',
    duration: '2:22:00',
    year: '1994',
    rating: '8.8',
    categoryId: 'motivation',
    psychTag: 'motivating',
    genres: 'Драма · Романтика',
    tags: {
      mood: ['inspire', 'anxiety', 'tired', 'cozy', 'distract'],
      genre: ['drama', 'romance', 'slice'],
      type: ['feature'],
      atmosphere: ['nostalgia', 'inspiring', 'warm', 'calm', 'light'],
    },
    description:
      'Эпическая история простодушия и стойкости. Напоминает, что важен путь, а не скорость - утешает и вдохновляет.',
    poster: 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/bLvqoHBptjg',
    watchUrl: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    country: 'США',
    director: 'Роберт Земекис',
    screenwriter: 'Эрик Рот',
  },
  {
    id: 'f16',
    title: 'Предложение',
    source: 'Touchstone Pictures',
    duration: '1:48:00',
    year: '2009',
    rating: '6.7',
    categoryId: 'burnout',
    psychTag: 'light',
    genres: 'Комедия · Романтика',
    tags: {
      mood: ['lift', 'cozy', 'distract', 'tired'],
      genre: ['comedy', 'romance', 'romcom'],
      type: ['feature'],
      atmosphere: ['light', 'warm', 'cozy_a', 'calm'],
    },
    description:
      'Лёгкая романтическая комедия с тёплым юмором. Помогает отвлечься и поднять настроение без лишнего напряжения.',
    poster: 'https://image.tmdb.org/t/p/w500/AcY6HVE7Wv6f0vU7q5tQJgM6Y5A.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/RFWqSVOcr-g',
    watchUrl: 'https://www.youtube.com/watch?v=RFWqSVOcr-g',
    country: 'США',
    director: 'Энн Флетчер',
    screenwriter: 'Питер Кьярелли',
  },
  {
    id: 'f17',
    title: '10 причин моей ненависти',
    source: 'Touchstone Pictures',
    duration: '1:37:00',
    year: '1999',
    rating: '7.3',
    categoryId: 'sleep',
    psychTag: 'light',
    genres: 'Комедия · Романтика',
    tags: {
      mood: ['lift', 'distract', 'cozy', 'inspire'],
      genre: ['comedy', 'romance', 'romcom'],
      type: ['feature'],
      atmosphere: ['light', 'warm', 'nostalgia', 'cozy_a'],
    },
    description:
      'Школьная романтическая комедия с остроумными диалогами. Лёгкий и уютный просмотр перед отдыхом.',
    poster: 'https://image.tmdb.org/t/p/w500/4wBG5kbfagTQclETblPRRGihk0I.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/uTIc58Eli_A',
    watchUrl: 'https://www.youtube.com/watch?v=uTIc58Eli_A',
    country: 'США',
    director: 'Джил Джунгер',
    screenwriter: 'Карен Маккалла, Кирстен Смит',
  },
  {
    id: 'f18',
    title: 'Школа рока',
    source: 'Paramount Pictures',
    duration: '1:50:00',
    year: '2003',
    rating: '7.2',
    categoryId: 'motivation',
    psychTag: 'motivating',
    genres: 'Комедия · Музыка',
    tags: {
      mood: ['lift', 'inspire', 'tired'],
      genre: ['comedy'],
      type: ['feature'],
      atmosphere: ['inspiring', 'light', 'warm'],
    },
    description:
      'Заряжает энергией и верой в свои силы. Подходит, когда хочется вдохновения и «включиться» на позитиве.',
    poster: 'https://upload.wikimedia.org/wikipedia/en/1/11/School_of_Rock_Poster.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/5afNkBuNUMI',
    watchUrl: 'https://www.youtube.com/watch?v=5afNkBuNUMI',
    country: 'США · Германия',
    director: 'Ричард Линклейтер',
    screenwriter: 'Майк Уайт',
  },
  {
    id: 'f19',
    title: 'Идеальный голос',
    source: 'Universal Pictures',
    duration: '1:52:00',
    year: '2012',
    rating: '7.1',
    categoryId: 'stress',
    psychTag: 'emotional_release',
    genres: 'Комедия · Музыка',
    tags: {
      mood: ['lift', 'distract', 'inspire', 'cozy'],
      genre: ['comedy', 'romcom'],
      type: ['feature'],
      atmosphere: ['light', 'warm', 'inspiring'],
    },
    description:
      'Весёлая история про хор и дружбу. Легко смотрится и помогает отвлечься от рутины.',
    poster: 'https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/8ljqXvIlg24',
    watchUrl: 'https://www.youtube.com/watch?v=8ljqXvIlg24',
    country: 'США',
    director: 'Джейсон Мур',
    screenwriter: 'Кей Кэннон',
  },
  {
    id: 'f20',
    title: 'Зверополис',
    source: 'Walt Disney Animation Studios',
    duration: '1:48:00',
    year: '2016',
    rating: '8.0',
    categoryId: 'anxiety',
    psychTag: 'emotional_release',
    genres: 'Анимация · Комедия',
    tags: {
      mood: ['lift', 'distract', 'inspire', 'anxiety', 'cozy'],
      genre: ['animation', 'family', 'comedy'],
      type: ['cartoon'],
      atmosphere: ['light', 'warm', 'inspiring', 'aesthetic', 'calm'],
    },
    description:
      'Яркий мультфильм с добрым посылом про принятие себя и других. Поднимает настроение и снимает напряжение.',
    poster: 'https://upload.wikimedia.org/wikipedia/en/9/96/Zootopia_%28movie_poster%29.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/j_0JUpKnY9M',
    watchUrl: 'https://www.youtube.com/watch?v=j_0JUpKnY9M',
    country: 'США',
    director: 'Байрон Ховард, Рич Мур',
    screenwriter: 'Джаред Буш, Фил Джонстон',
  },
  {
    id: 'f21',
    title: 'Рататуй',
    source: 'Pixar',
    duration: '1:51:00',
    year: '2007',
    rating: '8.1',
    categoryId: 'sleep',
    psychTag: 'light',
    genres: 'Анимация · Комедия',
    tags: {
      mood: ['cozy', 'relax', 'inspire'],
      genre: ['animation', 'family', 'comedy', 'slice'],
      type: ['cartoon'],
      atmosphere: ['aesthetic', 'warm', 'light', 'nostalgia', 'cozy_a', 'calm'],
    },
    description:
      'Тёплая история о мечте и творчестве. Создаёт уют и спокойное настроение после насыщенного дня.',
    poster: 'https://upload.wikimedia.org/wikipedia/en/5/50/RatatouillePoster.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/NgsQ8mVkN9w',
    watchUrl: 'https://www.youtube.com/watch?v=NgsQ8mVkN9w',
    country: 'США',
    director: 'Брэд Бёрд',
    screenwriter: 'Брэд Бёрд',
  },
  {
    id: 'f22',
    title: 'Кунг-фу Панда',
    source: 'DreamWorks Animation',
    duration: '1:32:00',
    year: '2008',
    rating: '7.6',
    categoryId: 'motivation',
    psychTag: 'motivating',
    genres: 'Анимация · Комедия',
    tags: {
      mood: ['lift', 'inspire', 'tired'],
      genre: ['animation', 'family', 'comedy', 'fantasy'],
      type: ['cartoon'],
      atmosphere: ['inspiring', 'light', 'warm', 'calm'],
    },
    description:
      'История про веру в себя и упорство - с юмором и драйвом. Хорошо заходит, когда нужна мотивация без мрака.',
    poster: 'https://upload.wikimedia.org/wikipedia/en/7/76/Kungfupanda.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/PXi3M627jcU',
    watchUrl: 'https://www.youtube.com/watch?v=PXi3M627jcU',
    country: 'США',
    director: 'Марк Осборн, Джон Стивенсон',
    screenwriter: 'Джонатан Айбел, Гленн Бергер',
  },
  {
    id: 'f23',
    title: 'Холодное сердце',
    source: 'Walt Disney Animation Studios',
    duration: '1:42:00',
    year: '2013',
    rating: '7.4',
    categoryId: 'sleep',
    psychTag: 'emotional_release',
    genres: 'Анимация · Фэнтези',
    tags: {
      mood: ['cozy', 'relax', 'inspire', 'anxiety'],
      genre: ['animation', 'family', 'fantasy'],
      type: ['cartoon'],
      atmosphere: ['aesthetic', 'warm', 'calm', 'cozy_a', 'inspiring'],
    },
    description:
      'Сказка про сестёр и принятие себя. Мягкий визуал и музыка помогают успокоиться и переключиться.',
    poster: 'https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/TbQm5doF_Uc',
    watchUrl: 'https://www.youtube.com/watch?v=TbQm5doF_Uc',
    country: 'США',
    director: 'Крис Бак, Дженнифер Ли',
    screenwriter: 'Дженнифер Ли',
  },
  {
    id: 'f24',
    title: 'Как приручить дракона',
    source: 'DreamWorks Animation',
    duration: '1:38:00',
    year: '2010',
    rating: '8.0',
    categoryId: 'motivation',
    psychTag: 'motivating',
    genres: 'Анимация · Приключения',
    tags: {
      mood: ['lift', 'inspire', 'cozy', 'distract'],
      genre: ['animation', 'family', 'fantasy'],
      type: ['cartoon'],
      atmosphere: ['aesthetic', 'warm', 'inspiring', 'light', 'nostalgia'],
    },
    description:
      'Про дружбу и смелость быть собой. Вдохновляет и дарит ощущение полёта - в хорошем смысле.',
    poster: 'https://upload.wikimedia.org/wikipedia/en/9/99/How_to_Train_Your_Dragon_Poster.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/Io4fbrAKbq0',
    watchUrl: 'https://www.youtube.com/watch?v=Io4fbrAKbq0',
    country: 'США',
    director: 'Крис Сандерс, Дин ДеБлоис',
    screenwriter: 'Уилл Дэвис, Крис Сандерс',
  },
  {
    id: 'f25',
    title: 'Мой сосед Тоторо',
    source: 'Studio Ghibli',
    duration: '1:26:00',
    year: '1988',
    rating: '8.1',
    categoryId: 'sleep',
    psychTag: 'antistress',
    genres: 'Анимация · Семейное',
    tags: {
      mood: ['relax', 'cozy', 'anxiety', 'distract'],
      genre: ['animation', 'family', 'fantasy'],
      type: ['anime', 'cartoon'],
      atmosphere: ['calm', 'cozy_a', 'aesthetic', 'nostalgia', 'warm'],
    },
    description:
      'Нежная история о детстве и природе. Очень спокойный ритм - как медитация перед сном.',
    poster: 'https://upload.wikimedia.org/wikipedia/en/0/02/My_Neighbor_Totoro_-_Tonari_no_Totoro_%28Movie_Poster%29.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/92a7Hj0ijLs',
    watchUrl: 'https://www.youtube.com/watch?v=92a7Hj0ijLs',
    country: 'Япония',
    director: 'Хаяо Миядзаки',
    screenwriter: 'Хаяо Миядзаки',
  },
  {
    id: 'f26',
    title: 'Ходячий замок',
    source: 'Studio Ghibli',
    duration: '1:59:00',
    year: '2004',
    rating: '8.2',
    categoryId: 'sleep',
    psychTag: 'light',
    genres: 'Анимация · Фэнтези',
    tags: {
      mood: ['relax', 'cozy', 'distract', 'inspire'],
      genre: ['animation', 'fantasy', 'romance'],
      type: ['anime', 'cartoon'],
      atmosphere: ['aesthetic', 'calm', 'warm', 'nostalgia', 'cozy_a'],
    },
    description:
      'Волшебная атмосфера Миядзаки про любовь и свободу. Красивый мир, в который приятно «уйти» от тревог.',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/23pkycRLhjY',
    watchUrl: 'https://www.youtube.com/watch?v=23pkycRLhjY',
    country: 'Япония',
    director: 'Хаяо Миядзаки',
    screenwriter: 'Хаяо Миядзаки',
  },
  {
    id: 'f27',
    title: 'Ведьмина служба доставки',
    source: 'Studio Ghibli',
    duration: '1:43:00',
    year: '1989',
    rating: '7.9',
    categoryId: 'anxiety',
    psychTag: 'antistress',
    genres: 'Анимация · Повседневность',
    tags: {
      mood: ['relax', 'anxiety', 'inspire', 'cozy'],
      genre: ['animation', 'fantasy', 'slice'],
      type: ['anime', 'cartoon'],
      atmosphere: ['calm', 'aesthetic', 'light', 'warm', 'cozy_a'],
    },
    description:
      'История взросления и самостоятельности - мягко и по-доброму. Помогает снизить внутреннее напряжение.',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/4b7ZFxNkHxd',
    watchUrl: 'https://www.youtube.com/watch?v=4b7ZFxNkHxd',
    country: 'Япония',
    director: 'Хаяо Миядзаки',
    screenwriter: 'Хаяо Миядзаки',
  },
  {
    id: 'f28',
    title: 'Ирония судьбы, или С лёгким паром!',
    source: 'Мосфильм',
    duration: '3:04:00',
    year: '1975',
    rating: '8.2',
    categoryId: 'burnout',
    psychTag: 'light',
    genres: 'Комедия · Мелодрама',
    tags: {
      mood: ['cozy', 'distract', 'inspire', 'relax', 'lift'],
      genre: ['comedy', 'romance', 'romcom', 'slice'],
      type: ['feature'],
      atmosphere: ['nostalgia', 'warm', 'light', 'cozy_a', 'calm'],
    },
    description:
      'Новогодняя классика про случайности и любовь. Уют, ностальгия и лёгкий юмор - как разговор с близкими.',
    poster: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/1hC_-xz0ka4',
    watchUrl: 'https://www.youtube.com/watch?v=1hC_-xz0ka4',
    country: 'СССР',
    director: 'Эльдар Рязанов',
    screenwriter: 'Эмиль Брагинский, Эльдар Рязанов',
  },
  {
    id: 'f29',
    title: 'Служебный роман',
    source: 'Мосфильм',
    duration: '2:39:00',
    year: '1977',
    rating: '8.2',
    categoryId: 'burnout',
    psychTag: 'light',
    genres: 'Комедия · Романтика',
    tags: {
      mood: ['lift', 'cozy', 'inspire', 'tired'],
      genre: ['comedy', 'romance', 'romcom', 'slice'],
      type: ['feature'],
      atmosphere: ['nostalgia', 'light', 'warm', 'cozy_a', 'calm'],
    },
    description:
      'Офисная история с тонким юмором и теплом. Ностальгия и лёгкость - хороший фон для отдыха после дел.',
    poster: 'https://image.tmdb.org/t/p/w500/9U7YHooiXv3xR3xBvY8QnD8QfJk.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/tS4BDX5BUQ0',
    watchUrl: 'https://www.youtube.com/watch?v=tS4BDX5BUQ0',
    country: 'СССР',
    director: 'Эльдар Рязанов',
    screenwriter: 'Эмиль Брагинский, Эльдар Рязанов',
  },
  {
    id: 'f30',
    title: 'Москва слезам не верит',
    source: 'Мосфильм',
    duration: '2:31:00',
    year: '1980',
    rating: '8.3',
    categoryId: 'motivation',
    psychTag: 'motivating',
    genres: 'Драма · Мелодрама',
    tags: {
      mood: ['inspire', 'tired', 'anxiety', 'cozy'],
      genre: ['drama', 'romance', 'slice'],
      type: ['feature'],
      atmosphere: ['nostalgia', 'inspiring', 'warm', 'calm', 'light'],
    },
    description:
      'История любви и карьеры в большом городе. Вдохновляет верить в себя и не сдаваться.',
    poster: 'https://image.tmdb.org/t/p/w500/lBYOKAMcxIvuk9s9hMuecB9dPBV.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/vfuKMiwJz_B',
    watchUrl: 'https://www.youtube.com/watch?v=vfuKMiwJz_B',
    country: 'СССР',
    director: 'Владимир Меньшов',
    screenwriter: 'Валентин Черных',
  },
  {
    id: 'f31',
    title: 'Интерстеллар',
    source: 'Paramount Pictures · Warner Bros.',
    duration: '2:49:00',
    year: '2014',
    rating: '8.7',
    categoryId: 'focus',
    psychTag: 'motivating',
    genres: 'Фантастика · Драма',
    tags: {
      mood: ['inspire', 'anxiety', 'distract', 'lift', 'tired'],
      genre: ['drama', 'fantasy', 'slice'],
      type: ['feature'],
      atmosphere: ['aesthetic', 'inspiring', 'calm', 'warm'],
    },
    description:
      'Масштабная история о времени, любви и выборе. Захватывает и заставляет по-новому смотреть на приоритеты.',
    poster: 'https://image.tmdb.org/t/p/w500/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/zSWdW4I0MUI',
    watchUrl: 'https://www.youtube.com/watch?v=zSWdW4I0MUI',
    country: 'США · Великобритания',
    director: 'Кристофер Нолан',
    screenwriter: 'Джонатан Нолан, Кристофер Нолан',
  },
];

export function getFilmById(id) {
  return FILMS.find((f) => f.id === id) || null;
}

export function posterToBackdropUrl(posterUrl) {
  if (!posterUrl || typeof posterUrl !== 'string') return '';
  return posterUrl.replace('/w500/', '/w1280/');
}
