import {
  Activity,
  Brain,
  Crosshair,
  Flame,
  Heart,
  Moon,
} from 'lucide-react';

export const FILM_CATEGORIES = [
  { id: 'burnout', labelKey: 'filmCatBurnout', Icon: Flame },
  { id: 'anxiety', labelKey: 'filmCatAnxiety', Icon: Brain },
  { id: 'stress', labelKey: 'filmCatStress', Icon: Activity },
  { id: 'sleep', labelKey: 'filmCatSleep', Icon: Moon },
  { id: 'focus', labelKey: 'filmCatFocus', Icon: Crosshair },
  { id: 'motivation', labelKey: 'filmCatMotivation', Icon: Heart },
];

export function filmSectionDescKey(categoryId) {
  return `filmSectionDesc${categoryId.charAt(0).toUpperCase() + categoryId.slice(1)}`;
}

/** @typedef {{ id: string, title: string, source: string, duration: string, year: string, rating: string, categoryId: string, psychTag: string, genres: string, description: string, poster: string, embedUrl: string, watchUrl: string, country?: string, director?: string, screenwriter?: string, gallery?: string[], quote?: string }} Film */

/** @type {Film[]} */
export const FILMS = [
  {
    id: 'f1',
    title: 'Soul',
    source: 'Pixar',
    duration: '1:40:00',
    year: '2020',
    rating: '8.0',
    categoryId: 'stress',
    psychTag: 'antistress',
    genres: 'Драма · Вдохновение',
    description:
      'Теплая история о смысле жизни, вдохновении и внутреннем спокойствии. Хорошо подходит, когда нужно мягко снизить тревогу.',
    poster: 'https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/xOsLIiBStEs',
    watchUrl: 'https://www.youtube.com/watch?v=xOsLIiBStEs',
    country: 'США',
    director: 'Пит Доктер, Кемп Пауэрс',
    screenwriter: 'Пит Доктер, Майк Джонс, Кемп Пауэрс',
  },
  {
    id: 'f2',
    title: 'The Secret Life of Walter Mitty',
    source: '20th Century Fox',
    duration: '1:54:00',
    year: '2013',
    rating: '7.3',
    categoryId: 'burnout',
    psychTag: 'motivating',
    genres: 'Приключения · Мотивация',
    description:
      'Фильм про внутренний перезапуск и смелость менять рутину. Отличный выбор при ощущении усталости и выгорания.',
    poster: 'https://image.tmdb.org/t/p/w500/cAh2pCiNPftsY3aSqJuIOde7uWr.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/HddkucqSzSM',
    watchUrl: 'https://rezka-ua.pub/films/adventures/1230-neveroyatnaya-zhizn-uoltera-mitti-2013.html',
    country: 'США',
    director: 'Бен Стиллер',
    screenwriter: 'Стив Конрад',
  },
  {
    id: 'f3',
    title: 'Spirited Away',
    source: 'Studio Ghibli',
    duration: '2:05:00',
    year: '2001',
    rating: '8.6',
    categoryId: 'sleep',
    psychTag: 'light',
    genres: 'Фэнтези · Спокойствие',
    description:
      'Медитативная атмосфера и красивый визуал помогают расслабиться перед сном и снизить внутреннее напряжение.',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ByXuk9QqQkk',
    watchUrl: 'https://www.youtube.com/watch?v=ByXuk9QqQkk',
    country: 'Япония',
    director: 'Хаяо Миядзаки',
    screenwriter: 'Хаяо Миядзаки',
    quote:
      'Иногда кажется, что всё вокруг — как во сне: что-то большее, чем просто красивый вид.',
  },
  {
    id: 'f4',
    title: 'The Social Network',
    source: 'Columbia Pictures',
    duration: '2:00:00',
    year: '2010',
    rating: '7.8',
    categoryId: 'focus',
    psychTag: 'motivating',
    genres: 'Биография · Фокус',
    description:
      'Динамичный, но структурный фильм, который помогает собраться и вернуть концентрацию перед работой или учебой.',
    poster: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/lB95KLmpLR4',
    watchUrl: 'https://www.youtube.com/watch?v=lB95KLmpLR4',
    country: 'США',
    director: 'Дэвид Финчер',
    screenwriter: 'Аарон Соркин',
  },
  {
    id: 'f5',
    title: 'Julie & Julia',
    source: 'Columbia Pictures',
    duration: '2:03:00',
    year: '2009',
    rating: '7.0',
    categoryId: 'burnout',
    psychTag: 'light',
    genres: 'Драма · Восстановление',
    description:
      'Легкий вдохновляющий сюжет про поиск себя и радость в простых шагах. Подходит для мягкого восстановления.',
    poster: 'https://image.tmdb.org/t/p/w500/AcY6HVE7Wv6f0vU7q5tQJgM6Y5A.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/DD8zMdn8LsQ',
    watchUrl: 'https://www.youtube.com/watch?v=DD8zMdn8LsQ',
    country: 'США',
    director: 'Нора Эфрон',
    screenwriter: 'Нора Эфрон',
  },
  {
    id: 'f6',
    title: 'Inside Out',
    source: 'Pixar',
    duration: '1:35:00',
    year: '2015',
    rating: '8.1',
    categoryId: 'anxiety',
    psychTag: 'emotional_release',
    genres: 'Психология · Эмоции',
    description: 'Фильм про эмоции и их принятие. Помогает лучше понять себя и снизить тревожные реакции.',
    poster: 'https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/yRUAzGQ3nSY',
    watchUrl: 'https://www.youtube.com/watch?v=yRUAzGQ3nSY',
    country: 'США',
    director: 'Пит Доктер, Роналдо Дель Кармен',
    screenwriter: 'Пит Доктер, Мег Лефов, Джош Кули',
  },
  {
    id: 'f7',
    title: 'The Intern',
    source: 'Warner Bros.',
    duration: '2:01:00',
    year: '2015',
    rating: '7.1',
    categoryId: 'burnout',
    psychTag: 'light',
    genres: 'Комедия · Поддержка',
    description:
      'Добрая история про баланс жизни и работы. Дает ощущение поддержки, когда эмоциональный ресурс на нуле.',
    poster: 'https://image.tmdb.org/t/p/w500/9U7YHooiXv3xR3xBvY8QnD8QfJk.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ZU3Xban0Y6A',
    watchUrl: 'https://www.youtube.com/watch?v=ZU3Xban0Y6A',
    country: 'США',
    director: 'Нэнси Майерс',
    screenwriter: 'Нэнси Майерс',
  },
  {
    id: 'f8',
    title: 'Midnight in Paris',
    source: 'Sony Pictures',
    duration: '1:34:00',
    year: '2011',
    rating: '7.6',
    categoryId: 'sleep',
    psychTag: 'light',
    genres: 'Романтика · Легкость',
    description:
      'Уютное настроение и мягкий темп помогают переключиться и подготовиться ко сну без перегруза.',
    poster: 'https://image.tmdb.org/t/p/w500/4wBG5kbfagTQclETblPRRGihk0I.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/FAfR8omt-CY',
    watchUrl: 'https://www.youtube.com/watch?v=FAfR8omt-CY',
    country: 'США · Франция',
    director: 'Вуди Аллен',
    screenwriter: 'Вуди Аллен',
  },
  {
    id: 'f9',
    title: 'A Beautiful Mind',
    source: 'Universal Pictures',
    duration: '2:15:00',
    year: '2001',
    rating: '8.2',
    categoryId: 'anxiety',
    psychTag: 'antistress',
    genres: 'Биография · Драма',
    description: 'Глубокая история о борьбе с тревогой и сохранении внутренней устойчивости в сложные периоды.',
    poster: 'https://image.tmdb.org/t/p/w500/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/aS_d0Ayjw4o',
    watchUrl: 'https://www.youtube.com/watch?v=aS_d0Ayjw4o',
    country: 'США',
    director: 'Рон Ховард',
    screenwriter: 'Акива Голдсман',
  },
  {
    id: 'f10',
    title: 'The Pursuit of Happyness',
    source: 'Columbia Pictures',
    duration: '1:57:00',
    year: '2006',
    rating: '8.0',
    categoryId: 'motivation',
    psychTag: 'motivating',
    genres: 'Мотивация · Драма',
    description:
      'Сильный мотивирующий фильм для периодов выгорания, когда важно вернуть веру в себя и свои шаги.',
    poster: 'https://image.tmdb.org/t/p/w500/lBYOKAMcxIvuk9s9hMuecB9dPBV.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/89Kq8SDyvfg',
    watchUrl: 'https://www.youtube.com/watch?v=89Kq8SDyvfg',
    country: 'США',
    director: 'Габриэле Муччино',
    screenwriter: 'Стив Конрад',
  },
  {
    id: 'f11',
    title: 'Up',
    source: 'Pixar',
    duration: '1:36:00',
    year: '2009',
    rating: '8.3',
    categoryId: 'sleep',
    psychTag: 'emotional_release',
    genres: 'Семейный · Теплый',
    description:
      'Очень мягкий и теплый фильм, который помогает снять эмоциональный фон и настроиться на спокойный сон.',
    poster: 'https://image.tmdb.org/t/p/w500/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ORFWdXl_zJ4',
    watchUrl: 'https://www.youtube.com/watch?v=ORFWdXl_zJ4',
    country: 'США',
    director: 'Пит Доктер, Боб Питерсон',
    screenwriter: 'Пит Доктер, Боб Питерсон',
  },
  {
    id: 'f12',
    title: 'Whiplash',
    source: 'Sony Pictures Classics',
    duration: '1:47:00',
    year: '2014',
    rating: '8.5',
    categoryId: 'stress',
    psychTag: 'emotional_release',
    genres: 'Музыка · Концентрация',
    description: 'Заряжает энергией и помогает сфокусироваться на цели. Хорошо подходит для режима продуктивности.',
    poster: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/7d_jQycdQGo',
    watchUrl: 'https://www.youtube.com/watch?v=7d_jQycdQGo',
    country: 'США',
    director: 'Дэмьен Шазелл',
    screenwriter: 'Дэмьен Шазелл',
  },
];

export function getFilmById(id) {
  return FILMS.find((f) => f.id === id) || null;
}

export function posterToBackdropUrl(posterUrl) {
  if (!posterUrl || typeof posterUrl !== 'string') return '';
  return posterUrl.replace('/w500/', '/w1280/');
}
