
export const SCROLL_REVEAL_SELECTORS = [
  '[data-scroll-reveal]',
  '.dashboard-new > *',
  '.dashboard-new .dash-widget',
  '.dashboard-new .dash-checkin-card',
  '.dashboard-new .dash-reco-item',
  '.dashboard-new .dash-support-card',
  '.practice-card',
  '.flix-film-card',
  '.events-flix-card',
  '.music-hub-section',
  '.music-hub-mood-card',
  '.music-hub-rec-card',
  '.articles-hub-section',
  '.articles-books-card',
  '.flix-catalog-section',
  '.flix-catalog-banner',
  '.meditation-hub-body .practice-card',
  '.podcast-hub-main .practice-card',
  '.land-bottom-info > section',
  '.land-bottom-banner',
  '.land-for-whom-showcase',
  '.land-bottom-formats-wrap',
  '.land-v2-footer-inner > *',
  '.land-v2-copy',
  '.land-v2-nav-pill',
  '.tests-page-hero',
  '.tests-catalog-card',
  '.test-card',
  '.take-test__step',
  '.stat-page > section',
  '.stat-card',
  '.profile-page > section',
  '.profile-page .card',
  '.ai-diary-panel',
  '.ai-diary-message',
  '.ai-chat-window .ai-msg',
  '.reading-book-detail > *',
  '.article-reader > *',
  '.article-reader-body > *',
  '.film-detail-section',
  '.event-detail-section',
  '.personalization-step',
  '.onb-survey-card > *',
  '.onb-result-card > *',
  '.auth-card > *',
  '.auth-card',
  '.admin-section .page-title',
  '.admin-section .admin-toolbar',
  '.admin-section .admin-table-wrap',
  '.admin-section .admin-stat-grid > *',
  '.admin-space-chrome',
  '.admin-space-panel > *',
  '.psych-section .card',
  '.psych-section .psych-stat',
  '.admin-portal-card',
  '.profile-settings-block',
  '.main-content > * > section',
  '.main-content > * > .card',
  '.main-content .page-title',
  '.main-content .page-sub',
  '.analytics-page > section',
  '.analytics-page .analytics-card',
  '.tests-mock-page--v2 > *',
  '.practices-page--hub > section',
  '.practices-sub-page > section',
  '.practices-favorites-page > section',
  '.diary-page > section',
  '.diary-page .card',
  '.onboarding-burnout > section',
  '.onboarding-burnout .card',
  '.personalization-page > *',
  '.music-hub > section',
  '.events-flix-page > section',
  '.flix-scope--catalog > section',
  '.meditation-hub > section',
  '.podcast-hub > section',
  '.reading-hub > section',
  '.auth-page > *',
  '.admin-portal-page > *',
].join(', ');

export const SCROLL_REVEAL_SKIP_SELECTOR = [
  '.modal-overlay',
  '.modal-overlay *',
  '[data-no-scroll-reveal]',
  '[data-no-scroll-reveal] *',
  '.loading-spinner',
  '.sidebar',
  '.sidebar *',
  '.land-glass-card',
  '.land-glass-typing-dots',
  '.land-glass-bubble',
  '.practices-landing--airy',
  '.ai-diary',
  '.ai-diary *',
  '.practice-card-fav',
  '.hub-cover-fav',
].join(', ');
